name: create a pull request for develop # 参考: https://elw.co.jp/blog/tech/github-actions-pr/
on:
  pull_request:
    types: [opened]
    branches: [stg]
jobs:
  action:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref != 'develop' #派生元がdevelopの場合は実行しない。develop->stg作成時に2重で作成されてしまうので。
    steps:
      - uses: actions/checkout@v3
      - name: Set variables # 変数設定
        run: |
          echo 'PR_BODY<<EOF' >> $GITHUB_ENV
          echo "#${{ github.event.pull_request.number }} から自動作成されたPR。${{ github.event.pull_request.head.ref }} → develop用。元のPRをApprovedすると、こちらも自動でApprovedされます。その後のマージは元PR作成者またはレビュワーが手動で対応お願いします。" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "---" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: pull-request # PR作成
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.event.pull_request.head.ref }}"
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: auto-pr-${{ github.event.pull_request.number }}
          pr_title: "[toDevelop] ${{ github.event.pull_request.title }}"
          pr_body: |
            ${{ env.PR_BODY }}