name: create a pull request for dev # 参考: https://elw.co.jp/blog/tech/github-actions-pr/
on:
  pull_request:
    types: [opened]
    branches: [stg]
jobs:
  action:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref != 'dev' #派生元がdevの場合は実行しない。dev->stg作成時に2重で作成されてしまうので。
    steps:
      - uses: actions/checkout@v3
      - name: Set variables
        run: |
          echo 'PR_BODY<<EOF' >> $GITHUB_ENV
          echo "the same as #${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "---" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.event.pull_request.head.ref }}"
          destination_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: dev
          pr_title: "${{ github.event.pull_request.title }}"
          pr_body: |
            ${{ env.PR_BODY }}
      - name: Labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "dev"
