name: Sync Auto PRs

on:
  pull_request:
    types: [synchronize]
    branches:
      - stg
      - prd

jobs:
  sync_prs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Define dynamic label based on the PR number
        run: echo "DYNAMIC_LABEL=auto-pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Print dynamic label
        run: echo $DYNAMIC_LABEL

      - name: Get PRs with the dynamic label
        run: |
          PR_LIST=$(gh pr list --label "$DYNAMIC_LABEL" --json number --jq '.[] | .number')
          echo "PR_LIST=$PR_LIST" >> $GITHUB_ENV

      - name: Print PR list
        run: echo $PR_LIST

      - name: Sync changes to other PRs
        run: |
          SOURCE_BRANCH=$(gh pr view ${{ github.event.pull_request.number }} --json headRefName --jq '.headRefName')
          echo $SOURCE_BRANCH
          for pr in $PR_LIST; do
            echo "Syncing changes to PR #$pr"
            TARGET_BRANCH=$(gh pr view $pr --json headRefName --jq '.headRefName')
            echo $TARGET_BRANCH
            git fetch origin $SOURCE_BRANCH:$SOURCE_BRANCH
            git checkout $TARGET_BRANCH
            git merge $SOURCE_BRANCH --no-ff --no-commit
            git commit -m "Merged changes from PR #${{ github.event.pull_request.number }} into PR #$pr"
            git push origin $TARGET_BRANCH
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
